export const products = [
  { id: 1, name: "She Blooms Graphic Tee", tagline: "Oversized · Lavender / White / Black", price: 2200, category: "tees", colors: ["#E8DEFF", "#FDFAF5", "#1A1625"], badge: "New", icon: "👕", description: "Soft ring-spun cotton, oversized fit. Features 'She Blooms' graphic on front." },
  { id: 2, name: "Malvie Logo Tee", tagline: "Oversized · Black / White", price: 2200, category: "tees", colors: ["#1A1625", "#FDFAF5"], badge: "Bestseller", icon: "👕", description: "Minimal logo print, 240GSM premium cotton." },
  { id: 3, name: "Botanical Line Art Tee", tagline: "Oversized · Cream / White", price: 2400, category: "tees", colors: ["#FDFAF5", "#FFFFFF"], badge: null, icon: "👕", description: "Delicate botanical line drawing. Relaxed silhouette." },
  { id: 4, name: "Born to Bloom Tee", tagline: "Oversized · Lavender / Black", price: 2800, category: "tees", colors: ["#C4A8E8", "#1A1625"], badge: "Limited", icon: "👕", description: "Statement typography tee. 'Born to Bloom' script." },
  { id: 5, name: "Minimal Canvas Bag", tagline: "Everyday essential", price: 3200, category: "bags", colors: ["#1A1625", "#FDFAF5"], badge: null, icon: "👜", description: "Durable canvas tote with inner pocket." },
  { id: 6, name: "Gold Accent Earrings", tagline: "Dainty & sophisticated", price: 1890, category: "jewelry", colors: ["#C9A96E"], badge: "Limited", icon: "✨", description: "Gold‑plated geometric earrings." },
  { id: 7, name: "Silk Scarf", tagline: "Premium finish", price: 2150, category: "lifestyle", colors: ["#B47DC8", "#C9A96E", "#FDFAF5"], badge: null, icon: "🧣", description: "Soft silk blend, hand‑rolled edges." },
  { id: 8, name: "Cream Classic Tee", tagline: "Timeless staple", price: 2200, category: "tees", colors: ["#FDFAF5", "#E8DEFF"], badge: null, icon: "👕", description: "Pure comfort, crew neck, slightly cropped." },
  { id: 9, name: "Ring Set", tagline: "Stack & shine", price: 1850, category: "jewelry", colors: ["#C9A96E"], badge: "Popular", icon: "💍", description: "Set of 3 adjustable rings." },
  { id: 10, name: "Plum Oversized Shirt", tagline: "Relaxed fit elegance", price: 2800, category: "tees", colors: ["#8B6BAF"], badge: null, icon: "🎽", description: "Button‑down shirt in plum, oversized." },
  { id: 11, name: "Sunglasses", tagline: "UV protection", price: 2500, category: "lifestyle", colors: ["#1A1625"], badge: null, icon: "👓", description: "Square acetate frames with UV400 lenses." },
  { id: 12, name: "Mini Pouch", tagline: "Compact & cute", price: 1200, category: "bags", colors: ["#E8DEFF", "#C9A96E"], badge: null, icon: "👝", description: "Zippered cosmetic pouch." },
  { id: 13, name: "Beaded Bracelet", tagline: "Spiritual vibes", price: 1650, category: "jewelry", colors: ["#B47DC8", "#E8DEFF"], badge: "New", icon: "📿", description: "Lavender howlite & gold beads." },
  { id: 14, name: "Lightweight Jacket", tagline: "Layering perfection", price: 3500, category: "tees", colors: ["#FDFAF5", "#1A1625"], badge: null, icon: "🧥", description: "Unlined cotton jacket, perfect for breezy evenings." },
  { id: 15, name: "Scented Candle", tagline: "Lavender essence", price: 1800, category: "lifestyle", colors: ["#E8DEFF"], badge: null, icon: "🕯️", description: "Soy wax candle with lavender & chamomile." }
];